Controllers/AtendimentoPedidoController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using ProjetoBacharelatoFilas.Repositories;

namespace ProjetoBacharelatoFilas.Controllers
{
    [Authorize]
    public class AtendimentoPedidoController : Controller
    {
        private readonly IPedidoServicoRepository _pedidoServicoRepository;

        public AtendimentoPedidoController(IPedidoServicoRepository pedidoServicoRepository)
        {
            _pedidoServicoRepository = pedidoServicoRepository;
        }

        public async Task<IActionResult> Index()
        {
            var pedidos = await _pedidoServicoRepository.Listar();

            return View(pedidos);
        }
    }
}

Controllers/FuncionarioController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using ProjetoBacharelatoFilas.Models;
using ProjetoBacharelatoFilas.Repositories;

namespace ProjetoBacharelatoFilas.Controllers
{
    [Authorize]
    public class FuncionarioController : Controller
    {
        private readonly IFuncionarioRepository _funcionarioRepository;

        private readonly IAuthenticate _authenticate;

        public FuncionarioController(IFuncionarioRepository funcionarioRepository, IAuthenticate authenticate)
        {
            _funcionarioRepository = funcionarioRepository;
            _authenticate = authenticate;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var result = await _funcionarioRepository.Listar();
            return View(result);
        }
        [HttpGet]
        public IActionResult Criar() => View();

        [HttpPost]
        public async Task<IActionResult> Criar(Funcionario funcionario)
        {
            var resultado = await _funcionarioRepository.Adicionar(funcionario);

            resultado = await _authenticate.RegisterUserAsync(funcionario.Email, GetFirstName(funcionario.NomeCompleto) + "123#".ToString(), await _funcionarioRepository.MaxFuncionario());

            return resultado ? RedirectToAction(nameof(Index)) : View(nameof(Criar), funcionario);
        }
        private static string GetFirstName(string fullName)
        {
            if (string.IsNullOrEmpty(fullName))
            {
                return string.Empty;
            }

            string[] names = fullName.Split(' ');

            return names[0];
        }
        [HttpGet]
        public async Task<IActionResult> Editar(int funcionarioId)
        {
            var resultado = await _funcionarioRepository.BuscarFuncionario(funcionarioId);
            return View(resultado);
        }
        [HttpPost]
        public async Task<IActionResult> Editar(Funcionario funcionario)
        {
            var resultado = await _funcionarioRepository.Editar(funcionario);

            return resultado ? RedirectToAction(nameof(Index)) : View(nameof(Editar), funcionario);
        }

        [HttpGet]
        public async Task<IActionResult> Eliminar(int funcionarioId)
        {
            var resultado = await _funcionarioRepository.Eliminar(funcionarioId);
            return RedirectToAction(nameof(Index));
        }

    }
}

Controllers/ServicoController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using ProjetoBacharelatoFilas.Helpers.Enum;
using ProjetoBacharelatoFilas.Models;
using ProjetoBacharelatoFilas.Repositories;
using ProjetoBacharelatoFilas.ViewModels;
using iTextSharp.LGPLv2.Core;
using iTextSharp.text;
using iTextSharp.text.pdf;
namespace ProjetoBacharelatoFilas.Controllers
{
    [Authorize]
    public class ServicoController : Controller
    {
        private readonly IServicoRepository _servicoRepository;
        private readonly IPedidoServicoRepository _pedidoServicoRepository;
        private readonly IEstudanteRepository _estudanteRepository;
        private readonly IModeloSenhaRepository _modeloSenhaRepository;
        private readonly IWebHostEnvironment _webHostEnvironment;
        public ServicoController(IServicoRepository servicoRepository, IPedidoServicoRepository pedidoServicoRepository, IEstudanteRepository estudanteRepository, IModeloSenhaRepository modeloSenhaRepository, IWebHostEnvironment webHostEnvironment)
        {
            _servicoRepository = servicoRepository ?? throw new ArgumentNullException(nameof(servicoRepository));
            _pedidoServicoRepository = pedidoServicoRepository;
            _estudanteRepository = estudanteRepository;
            _modeloSenhaRepository = modeloSenhaRepository;
            _webHostEnvironment = webHostEnvironment;
        }


        [AllowAnonymous]
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var servicos = await _servicoRepository.Listar();
            return View(servicos);
        }

        [HttpGet]
        public async Task<IActionResult> Listagem()
        {
            var servicos = await _servicoRepository.Listar();
            return View(servicos);
        }

        [HttpGet]
        public IActionResult Criar()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Criar(Servico servico)
        {
            var resultado = await _servicoRepository.Adicionar(servico);

            return resultado ? RedirectToAction(nameof(Listagem)) : View(nameof(Criar), servico);
        }
        [HttpGet]
        public async Task<IActionResult> Editar(int servicoId)
        {
            var resultado = await _servicoRepository.BuscarServico(servicoId);
            ViewData["Estados"] = Enum.GetValues(typeof(Estado));
            return View(resultado);
        }
        [HttpPost]
        public async Task<IActionResult> Editar(Servico servico)
        {
            var resultado = await _servicoRepository.Editar(servico);

            return resultado ? RedirectToAction(nameof(Listagem)) : View(nameof(Editar), servico);
        }

        [HttpGet]
        public async Task<IActionResult> Eliminar(int servicoId)
        {
            var resultado = await _servicoRepository.Eliminar(servicoId);
            return RedirectToAction(nameof(Listagem));
        }
        [AllowAnonymous]
        [HttpGet]
        public IActionResult Formulario(int servicoId)
        {
            var form = new FormularioViewModel { ServicoId = servicoId };
            return View(form);
        }

        [AllowAnonymous]
        [HttpPost]
        public async Task<IActionResult> EfetuarPedido(FormularioViewModel servico)
        {
            var response = await _modeloSenhaRepository.Adicionar();
            var pedido = new PedidoServico
            {
                ServicoId = servico.ServicoId,
                NomeCompleto = servico.Estudante.NomeCompleto,
                Email = servico.Estudante.Email,
                Telefone = servico.Estudante.Telefone,
                Curso = servico.Estudante.Curso,
                SenhaPedido = response.Senha,
                Servico = await _servicoRepository.BuscarServico(servico.ServicoId)
            };
            await _pedidoServicoRepository.Adicionar(pedido);

            return View(nameof(ConfirmacaoPedido), pedido);
        }
        [AllowAnonymous]
        [HttpGet]
        public IActionResult ConfirmacaoPedido()
        {
            return View();
        }
        [AllowAnonymous]
        public async Task<IActionResult> PdfGerar(int id)
        {
            var pedidoServico = await _pedidoServicoRepository.BuscarPedidoServicoAsync(id);

            var webRootPath = _webHostEnvironment.WebRootPath;

            MemoryStream memoryStream = new MemoryStream();
            Document document = new Document(PageSize.A4, 25, 25, 25, 25);
            PdfWriter pdfWriter = PdfWriter.GetInstance(document, memoryStream);
            document.Open();

            var imagePath = Path.Combine(webRootPath, "img", "instic-logo-1.png");

            Image logo = Image.GetInstance(imagePath);
            logo.ScalePercent(10f);
            logo.Alignment = Element.ALIGN_CENTER;
            document.Add(logo);
            Paragraph space = new Paragraph($"\n\n\n\n\n");
            space.Alignment = Element.ALIGN_CENTER;
            space.Font = new Font(Font.HELVETICA, 13, Font.BOLD, BaseColor.Blue);
            document.Add(space);
            Paragraph companyName = new Paragraph($"Estudante:{pedidoServico.NomeCompleto}");
            companyName.Alignment = Element.ALIGN_CENTER;
            companyName.Font = new Font(Font.HELVETICA, 13, Font.BOLD, BaseColor.Blue);
            document.Add(companyName);

            Paragraph senha = new Paragraph($"Senha:{pedidoServico.SenhaPedido}");
            senha.Alignment = Element.ALIGN_CENTER;
            senha.Font = new Font(Font.HELVETICA, 13, Font.BOLD, BaseColor.Blue);
            document.Add(senha);

            Paragraph servico = new Paragraph($"Serviço:{pedidoServico.Servico.NomeServico}");
            servico.Alignment = Element.ALIGN_CENTER;
            servico.Font = new Font(Font.HELVETICA, 13, Font.BOLD, BaseColor.Blue);
            document.Add(servico);

            document.Add(new Paragraph("\n"));
            Paragraph mesAvaliacao = new Paragraph($"Data Emissão:{pedidoServico.DataCriacao.ToShortDateString()}");
            mesAvaliacao.Alignment = Element.ALIGN_CENTER;
            mesAvaliacao.Font = new Font(Font.HELVETICA, 16, Font.BOLD, BaseColor.Blue);
            document.Add(mesAvaliacao);

            document.Add(new Paragraph("\n"));

            document.Close();

            byte[] pdfContent = memoryStream.ToArray();
            return new FileContentResult(pdfContent, "application/pdf");
        }
        
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ProjetoBacharelatoFilas</title>
    <!-- bootstrap core css -->
    <link rel="stylesheet" type="text/css" href="~/lib/bootstrap/dist/css/bootstrap.css" />

    <!-- fonts style -->

    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700;900&display=swap" rel="stylesheet">

    <!--owl slider stylesheet -->
    <link rel="stylesheet" type="text/css"
          href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css" />

    <!-- font awesome style -->
    <link href="~/lib/bootstrap/dist/css/font-awesome.min.css" rel="stylesheet"/>
    
    <!-- Custom styles for this template -->
    <link href="~/lib/bootstrap/dist/css/style.css" rel="stylesheet" />
    <!-- responsive style -->
    <link href="~/lib/bootstrap/dist/css/responsive.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/1.13.5/css/jquery.dataTables.css" />

  

</head>
<body>
        <!-- header section strats  #00204a -->
        <header class="header_section" style="background-color: #00204a !important;">
            <div class="container-fluid">
                <nav class="navbar navbar-expand-lg custom_nav-container ">
                    <a class="navbar-brand" asp-action="Index" asp-controller="Home">
                        <img src="~/img/instic-logo-1.png" alt="instic-logo" width="150">
                    </a>

                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class=""> </span>
                    </button>

                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav  ">
                            <li class="nav-item active">
                            <a class="nav-link" asp-action="Index" asp-controller="Home">Home <span class="sr-only">(current)</span></a>
                            </li>
                            <li class="nav-item">
                            <div class="dropdown">
                                <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Gerenciamento
                                </button>
                                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                    <a class="dropdown-item" asp-action="Index" asp-controller="AtendimentoPedido">Pedidos</a>
                                    <a class="dropdown-item" asp-action="Index" asp-controller="Funcionario">Funcionários</a>
                                    <a class="dropdown-item" asp-action="Listagem" asp-controller="Servico">Serviços</a>
                                </div>
                            </div>
                            </li>
                            <li class="nav-item">
                            <a class="nav-link" asp-action="Sobre" asp-controller="Home"> Sobre</a>
                            </li>
                            <li class="nav-item">
                            <a class="nav-link" asp-action="Index" asp-controller="Servico">Serviços</a>
                            </li>



                            <li class="nav-item">
                            <a class="nav-link" asp-action="Equipe" asp-controller="Home">Nossa Equipa</a>
                            </li>
                            <li class="nav-item">
                            <a class="nav-link"  asp-action="Login" asp-controller="Account"> <i class="fas fa-user" aria-hidden="true"></i> Login</a>
                            </li>
                            <form class="form-inline">
                                <button class="btn  my-2 my-sm-0 nav_search-btn" type="submit">
                                    <i class="fa fa-search" aria-hidden="true"></i>

                                </button>
                            </form>
                        <li class="nav-item">
                            <a class="nav-link" asp-action="Logout" asp-controller="Account">Sair</a>
                        </li>
                        </ul>
                    </div>
                </nav>
            </div>
        </header>
        <!-- end header section -->
      
    @* </div> *@

   
    <!-- end client section -->
    

    @* 
    <div class="container-expand">
        <main role="main"> *@
            @RenderBody()
        @* </main>
    </div> *@

    <!-- info section -->

    <section class="info_section layout_padding2">
        <div class="container">
            <div class="row">

                <div class="col-md-6 col-lg-3 info_col">
                    <div class="info_detail">
                        <img src="~/img/instic-logo-1.png" alt="" width="250" height="100">
                    </div>
                </div>

                <div class="col-md-6 col-lg-3 info_col">
                    <div class="info_contact">
                        <h4>
                            Endereço
                        </h4>
                        <div class="contact_link_box">
                            <a href="">
                                <i class="fa fa-map-marker" aria-hidden="true"></i>
                                <span>
                                    Bairro CTT Km 7,Rangel-Luanda
                                </span>
                            </a>
                            <a href="">
                                <i class="fa fa-phone" aria-hidden="true"></i>
                                <span>
                                    Contacto 222041728
                                </span>
                            </a>
                            <a href="">
                                <i class="fa fa-envelope" aria-hidden="true"></i>
                                <span>
                                    instic2020@gmail.com
                                </span>
                            </a>
                        </div>
                    </div>
                    <div class="info_social">
                        <a href="">
                            <i class="fa fa-facebook" aria-hidden="true"></i>
                        </a>
                        <a href="">
                            <i class="fa fa-twitter" aria-hidden="true"></i>
                        </a>
                        <a href="">
                            <i class="fa fa-linkedin" aria-hidden="true"></i>
                        </a>
                        <a href="">
                            <i class="fa fa-instagram" aria-hidden="true"></i>
                        </a>
                    </div>
                </div>

                <div class="col-md-6 col-lg-2 mx-auto info_col">
                    <div class="info_link_box">
                        <h4>
                            Links
                        </h4>
                        <div class="info_links">
                            <a class="active" asp-action="Index" asp-controller="Home">
                                Home
                            </a>
                            <a class="" asp-action="Sobre" asp-controller="Home">
                                Sobre
                            </a>
                            <a class="" asp-action="Servico" asp-controller="Home">
                                Serviços
                            </a>
                            <a class="" asp-action="Equipe" asp-controller="Home">
                                Nossa Equipa
                            </a>
                        </div>
                    </div>
                </div>
                <div class="col-md-6 col-lg-3 info_col ">
                    <h4>
                        Acessar Conta
                    </h4>
                    <form action="#">
                        <button type="submit" asp-controller="Account" asp-action="Login">
                            LOGIN
                        </button>
                        <button type="submit" asp-controller="Account" asp-action="Register">
                            CADASTRAR
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </section>

    <!-- end info section -->
    <!-- footer section -->
    <section class="footer_section">
        <div class="container">
            <p>
                &copy; <span id="displayYear"></span> Todos os direitos reservados -
                <a href="index.html"> INSTIC</a>
            </p>
        </div>
    </section>
    <!-- end footer section -->
    <!-- jQery -->
    <script type="text/javascript" src="~/js/jquery-3.4.1.min.js"></script>
    <!-- popper js -->
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
            integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous">
    </script>
    <!-- bootstrap js -->
    <script type="text/javascript" src="~/js/bootstrap.js"></script>
    <!-- owl slider -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js">
    </script>
    <!-- custom js -->
    <script type="text/javascript" src="~/js/custom.js"></script>
    <!-- Google Map -->
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCh39n5U-4IoWpsVGUHWdqB6puEkhRLdmI&callback=myMap">
    </script>
    <script src="https://cdn.datatables.net/1.13.5/js/jquery.dataTables.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
   
</body>
</html>